### ISSUE TITLE
Purging extension takes hours

### ISSUE THREAD

**Issue by ser** [AlfredoRamos/phpbb-ext-markdown#70]
Hi, purging extension takes literally hours on my large forum, is it really required? I can see thousands of SQL updates per second.

**Comment by AlfredoRamos** [comment]
Hi,

> purging extension takes literally hours on my large forum

Not sure what you mean by "purging extension", but if you mean disabling/enabling the extension, it doesn't take more than a couple of seconds.

If you mean purging the cache in the ACP, it's almost instantaneous.

Otherwise you would need to elaborate on what "purging extension" supposed to mean.

I manage two boards with 150M and 270M posts, without any slowdown while using it or enabling/disabling it.

> I can see thousands of SQL updates per second

Really strange, since this extension does not make any SQL query directly, and the ones it generates are very standard, to create/delete configuration records, permissions and a single table column, and they are not that many.

Providing information about those SQL updates would have been helpful.

**Comment by ser** [comment]
what i mean is

```php phpbbcli.php extension:purge alfredoramos/markdown``

OK - I will try to inspect then what these updates do - maybe it is related to other installed extensions? I will report back soon, thanks!
